### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [Stanwukong/ecomm-lykdat-clone#2]
Hello!!
I am a beginner and I would like t update the README

**Comment by Stanwukong** [comment]
> Hello!!
> I am a beginner and I would like t update the README 

Can you please elaborate on what you mean?

**Comment by the-amazing-atharva** [comment]
For example : 
![image](https://user-images.githubusercontent.com/121221252/214740586-d70089cf-0632-474e-ac83-604ac793774b.png)


Have more things to add. If you liked this update do tell me !!!

**Comment by the-amazing-atharva** [comment]
Thoughts @Stanwukong ?

**Comment by Stanwukong** [comment]
> Thoughts @Stanwukong ?

@the-amazing-atharva no problem, what do you need?

**Comment by the-amazing-atharva** [comment]
Nothing sorry

Sending a PR soon

> > Thoughts @Stanwukong ?
> 
> @the-amazing-atharva no problem, what do you need?
